Error CS0414 in project AGSEditor, file StatisticsSenderComponent.cs
Variables is assigned to, but value is never used. We simply disable the warning with a pragma statement to make sure nothing breaks.