Error CS0414 in project AGS.Types, file DialogOption.cs
xBuild doesn't approve of unused variable, removed it and a added DeserializeIgnore to class to make sure deserializing doesn't break

ggg