Script API: default VOID functions return value to "integer 0"
AGS script compiler was always giving extra "freedom" to the script writers and did not protest against using return values of functions that were not actually supposed to return anything. For some time there was no "void" return value in script at all, and functions were declared having type "function" which translates as "returning integer". Even after "void" was introduced, a lot of existing API still is declared as "function". But internally engine implements many of these as "void".

And even if function is declared as "void" today compiler still fails to prevent using return value at all times. E.g. while int a = Game.StopAudio(); will trigger compilation error, but if (Game.StopAudio() == 0) will not! Which is a compiler's bug of course, but that's a separate issue.

What this means is that in theory there may be older games out there that are using "void" function's return values by mistake. Original engine did not care (which probably caused undefined behavior when C++ program tried to assign void function's return value to integer), but in the modern engine such attempts get intercepted and game is shut down with error.

Problem is that this ironically may prevent particular old games from working. I found this issue after someone reported a bug in the "Quest for Glory II" VGA version by AGDI, where script was trying to test a return value of a void function "InterfaceOn". AGS 3.4.1 stops game with error: internal error: undefined value pushed to stack.