Error CS0219 in project AGSEditor, file ImportExport.cs
Two unused variables at the end of scope. I commented out the variables declarations and kept the initialization since the the variables were initiated with a binary reader that will throw off the format if it is not kept in code.